spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/book_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google OAuth 2.0 Configuration
spring.security.oauth2.client.registration.google.client-id=971292960309-rtuuqnq28gl7m5ptjd6ap0ub8am8gmq1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# OAuth2 Redirect Configuration
oauth2.redirect-url=http://localhost:5173/profile

